name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: libmmo
      - name: Checkout common project
        uses: actions/checkout@v2
        with:
          repository: hollow-cube/common
          path: common
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Grant execute permission for gradlew
        working-directory: libmmo
        run: chmod +x gradlew
      - name: Setup gradle cache
        uses: burrunan/gradle-cache-action@v1
        with:
          save-generated-gradle-jars: false
          save-local-build-cache: false
          save-gradle-dependencies-cache: true
          save-maven-dependencies-cache: true
          # Ignore some of the paths when caching Maven Local repository
          maven-local-ignore-paths: |
            starlight/mmo/
      - name: Build
        working-directory: libmmo
        run: ./gradlew classes testClasses
      - name: Run tests
        working-directory: libmmo
        run: ./gradlew test
